safe: true
timezone: "Europe/Oslo"
highlighter: rouge
markdown: rdiscount
lsi: true

#permalink: /:title/


defaults:
  -
    scope:
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: "_posts/no"
    values:
      lang: "no"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  #-
  #  scope:
  #    type: "pages"
  #  values:
